import type { Metadata } from "next";

import { Instrument_Sans } from "next/font/google";
import "./globals.css";
const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-dl-neutral-200">
      <body className={`${instrumentSans.className} h-screen flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
